cynkra/dm

DESCRIPTION
R/db-helpers.R
R/filter-helpers.R
R/foreign-keys.R
R/key-helpers.R
R/primary-keys.R
R/utils.R
tests/testthat/helper-src.R
tests/testthat/test-foreign-key-functions.R
tests/testthat/test-primary-key-functions.R

- `enum_pk_candidates()`, `cdm_enum_pk_candidates()` and `cdm_enum_fk_candidates()` explain now rejections in a new column `why` (admittedly rather superficially)

explain rejected candidates

---

R/db-helpers.R
R/db-interface.R
R/dm.R
R/draw-dm.R
R/error-helpers.R
R/foreign-keys.R
R/primary-keys.R
R/utils.R
man/cdm_get_all_fks.Rd
tests/testthat/test-learn-from-database.R

More work needs to be done, along the lines of the commits in this PR. Search for `cdm_get_data_model(` and replace accordingly.
Closes #25.

Simplify updating dm objects

---

R/dm.R

``` r
library(tibble)
t <- tibble(a = rep(0, 3))
length(unique(t[t$a != 0, "a"]))
#> [1] 1
df <- as.data.frame(t)
length(unique(df[df$a != 0, "a"]))
#> [1] 0
```
<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

new {datamodelr} print method does not well with tibbles

---

R/filter-helpers.R
tests/testthat/test-filter-helper.R

Description of the function promises a named list, but the sum of the row numbers was returned instead.

return named list with `cdm_nrow()`?

---

R/data-model-helpers.R
R/dm.R
R/error-helpers.R
R/flatten.R
R/graph.R
man/cdm_flatten_to_tbl.Rd
tests/testthat/helper-src.R
tests/testthat/test-flatten.R

- minimized disambiguation (disambiguate after selecting relevant tables)
- ellipsis taking dimension tables as argument
- fact-table is for some joins the only table that is affected by filters
closes #62
One question remains for me: I could imagine, that a user who - in the example of `dm_for_flatten` - sets filters and then uses `cdm_flatten_to_tbl()`:
```r
cdm_filter(dm_for_flatten, dim_1, dim_1_pk > 6) %>% 
cdm_filter(dim_2, dim_2_pk %in% letters[4:10]) %>% 
cdm_flatten_to_tbl(fact, dim_1, dim_2, join = right_join)
```
might not want the filter on table `dim_1` to affect table `dim_2` and vice versa. One could think of having the filters just affect the respective tables in `ordered_table_list` and not have a cascading effect.
another thing is, that the order of the tables in the …

reorganize `cdm_flatten()`

---

R/db-interface.R
R/dm.R
R/draw-dm.R
R/error-helpers.R
R/foreign-keys.R
R/learn_dm_from_db.R
R/primary-keys.R
R/select_tables_from_dm.R
R/utils.R
README.Rmd
README.md
man/dm.Rd
tests/testthat/test-select.R
vignettes/dm-class-and-basic-operations.Rmd
vignettes/dm.Rmd

- remove `src` from `dm`
-  add some checks for same src of tables
- add 2 classed errors
- `cdm_get_src()` for local `dm` returns `.GlobalEnv`
closes #38

remove src from `dm` since implicitly available

---

R/error-helpers.R
R/key-helpers.R
tests/testthat/test-check-key.R

`check_key()` now deals correctly with named column lists

repair behaviour for named character vector as param for 'check_key()'

---

R/db-helpers.R
R/db-interface.R
R/error-helpers.R
R/test-dm.R
man/cdm_copy_to.Rd
tests/testthat/test-filter-dm.R

@TSchiefer: Can you please pick up from here?
- Document argument, note that all table names are quoted with `dbplyr::ident_q()`
- Add tests

New table_names argument to cdm_copy_to()

---

R/disambiguate.R
R/flatten.R
R/graph.R
tests/testthat/test-flatten.R

- `cdm_flatten_to_tbl()` determines now the correct neighbourhood
- avoided the meaningless message ("Joining, by ...") when calling `cdm_flatten_to_tbl()` or `cdm_squash_to_tbl()`
fixes #95

correctly flatten neighbourhood

---

R/add-tbl.R
R/dm.R
R/select-tbl.R
man/dm.Rd
tests/testthat/helper-src.R
tests/testthat/test-add-tbl.R
tests/testthat/test-dm.R

- Empty object can be created via `dm()` and `new_dm()` (without arguments, similar to `numeric()`, `list()`, etc.)
- Allows for creation of a `dm` from scratch, adding tables successively with `cdm_add_tbl()`
- Works locally and on DB
- vignettes have NOT been adapted

provide empty 'dm' object

---

R/add-tbl.R
tests/testthat/test-add-tbl.R

- consistent types in `def` columns
(e.g. `cdm_select_tbl()` doesn't work otherwise)

bugfix for 'cdm_add_tbl()'

---

vignettes/dm-class-and-basic-operations.Rmd
vignettes/dm.Rmd

This is just a hotfix, so R_CMD_check doesn't throw an error. We need to rework the vignettes as soon as we're at a stable state

avoid 'cdm_get_data_model()' in vignettes

---

R/select-tbl.R
tests/testthat/test-select-tbl.R

currently on master:
``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
cdm_nycflights13(cycle = TRUE) %>% cdm_draw()
```
``` r
cdm_select_tbl(cdm_nycflights13(cycle = TRUE), flights, airports) %>% cdm_draw()
```
<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
in this branch:
``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
cdm_nycflights13(cycle = TRUE) %>% cdm_draw()
```
``` r
cdm_select_tbl(cdm_nycflights13(cycle = TRUE), flights, airports) %>% cdm_draw()
```
<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Bugfix: `cdm_select_tbl()` with multi-FKs between 2 tables

---

R/dm.R
R/dplyr.R
R/error-helpers.R
R/filter-dm.R
R/filter-helpers.R
R/foreign-keys.R
R/primary-keys.R
R/select-tbl.R
R/select.R
man/cdm_filter.Rd
tests/testthat/test-dplyr.R
tests/testthat/test-flatten.R

when setting a filter (either with `cdm_filter()` or `cdm_zoom_to_tbl()` - `filter()`) the table that is filtered will be actually filtered immediately. In addition, the filter-expression is stored.
1. users can still access their filter conditions (also available in `print()`-method)
2. no problems anymore with changing column names etc.
3. effect on all other tables needs to be invoked via `cdm_apply_filters()` or `compute.dm()`
fixes #124 
fixes #113 ?

instant filter for filter-table

---

R/dplyr.R
R/zoom.R
tests/testthat/helper-src.R
tests/testthat/test-dplyr.R
tests/testthat/test-select-tbl.R

problem was `set_names(NULL)` would throw an error
- helper function `set_names_or_null()`
- test for the failing case
@krlmlr this patch is necessary for the demo.

bugfix: 'mutate.zoomed_dm()' when no keys are tracked

---

R/dm.R

works with `structure()` for `tbl_dbi`, but needs a workaround for local tibbles

avoid star when printing local 'zoomed_dm'

---

R/dplyr.R
R/error-helpers.R
tests/testthat/test-dplyr.R

- now drops potential primary key if positive indices are repeated
- now only accepts integer and numeric vectors without any decimal place different from `0`
fixes #151

Bugfix: key tracking for 'slice()'-method

---

R/primary-keys.R
tests/testthat/test-primary-keys.R

Is currently like this on master:
``` r
suppressPackageStartupMessages({
library(dm)
library(tibble)
})
t3 = tibble(f = LETTERS[5:7], g = c("four", "five", "six"))
t4 = tibble(h = letters[3:5], i = c("five", "six", "seven"), j = c("E", "F", "F"))
t5 = tibble(
k = 2:4,
l = letters[3:5],
m = c("tree", "streetlamp", "streetlamp")
)
test_dm <- dm(t3, t4, t5) %>% 
cdm_add_pk(t4, h) %>% 
cdm_add_pk(t3, f) %>% 
cdm_add_fk(t5, l, t4) %>% 
cdm_add_fk(t4, j, t3)
cdm_draw(test_dm)
```
``` r
cdm_rm_pk(test_dm, t4, rm_referencing_fks =TRUE) %>% 
cdm_draw
```
<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
But should be like this (this branch):
``` r
suppressPackageStartupMessages({
library(dm)
library(tibble)
})
t3 = tibble(f = LETTERS[5:7], g = …
```

Small-ish bug in 'cdm_rm_pk()'

---

vignettes/dm-class-and-basic-operations.Rmd
vignettes/dm-filtering.Rmd
vignettes/dm-introduction-relational-data-models.Rmd
vignettes/dm-visualization.Rmd
vignettes/dm.Rmd

Two code examples throw an error (could not find function "dm_from_src") when knitting the vignettes that contain them.
Please suggest a fix for the error and review my changes.
Closes #170.

Removed data_model components in vignettes (Issue #170)

---

R/filter-dm.R
R/graph.R
tests/testthat/test-filter-dm.R
tests/testthat/test-flatten.R
tests/testthat/test-graph.R

For the test we check in an induced subgraph of all connected tables/nodes (related to one "start" table) if `N(E(graph)) >= N(V(graph))`
The only problem is, that we are sometimes too strict: assume a graph `(t1 - t2, t2 - t3, t3 - t4, t4 - t2)` and we filter `t1` and we request `t2`, then it fails cause the subgraph consists of `(t1, t2, t3, t4)`. But, if we want to resolve this properly, we might need to work with something like `igraph::all_simple_paths()` for many pairs of tables, which would slow down things quite a bit. So I tend to think, that this solution here is not so bad.
Tests are included in this PR.
addresses 2nd part of issue #150

test for cycle in 'get_all_filtered_connected()'

---

R/dplyr.R
R/error-helpers.R
R/flatten.R
R/foreign-keys.R
R/primary-keys.R
R/select-tbl.R
R/test-dm.R
tests/testthat/out/error-msgs.txt
tests/testthat/test-dm-dplyr.R
tests/testthat/test-dm-flatten.R

- tweaking error issuing and messages
closes #220 
At the time of the PR there is still some inexplicable difference between `dm_select_tbl()` and `dm_rename_tbl()` which could be fixed by a hack, but IMO there should be an easier solution:
``` r
suppressPackageStartupMessages(library(dm))
dm_flights <- dm_nycflights13()
dm_select_tbl(dm_flights, f = mtcars)
#> Error: `mtcars` must evaluate to table positions or names, not a list. Available tables in `dm`: `airlines`, `airports`, `flights`, `planes`, `weather`
dm_rename_tbl(dm_flights, f = mtcars)
#> Error: `f` = structure(list(mpg = c(21, 21, 22.8, 21.4, 18.7, 18.1, 14.3, 
#> 24.4, 22.8, 19.2, 17.8, 16.4, 17.3, 15.2, 10.4, 10.4, 14.7, 32.4, 
#> 30.4, 33.9, 21.5, 15.5, 15.2, 13.3, 19.2, 27.3, 26, 30.4, 15.8, 
#> 19.7, 15, 21.4), cyl = …
```

Improve error messages for missing tables

---

R/dm.R
R/dplyr.R
R/global.R
R/key-helpers.R
R/learn.R
R/primary-keys.R
R/select.R
R/test-dm.R
R/tidyr.R
R/zoom.R
tests/testthat/helper-zoom.R
tests/testthat/test-dm-dm.R
tests/testthat/test-dm-dplyr.R
tests/testthat/test-dm-zoom.R

should be quicker eventually:
- all columns are tracked of zoomed_table
- columns are removed from tracker under certain circumstances (mutate, deselect, etc.)
- if all columns are still tracked all keys will remain:
This feature is only available for `dm_update_zoomed()`, since we need to access the key columns of the original table specifically when using `dm_insert_zoomed()` in order to replicate the keys for the new table
closes #266

better zoomed tracking

---

R/dm.R

(See #307 for background.)
While poking around to create a precise issue for dbplyr, I realized that `db_desc()` is also exposed via `dplyr::tbl_sum()` where it is called without the expensive `src_tbls()` call.
This PR modified `print.dm` to call `dplyr::tbl_sum()` on one table in the dm object and use the `"Database"` entry.
If no tables are included in the dm object, it falls back to the previous `dbplyr::format.src_sql()` approach.
With my test case, the timing went down, um, _considerably_. It turns out the previous approach took about 15 seconds on average. This new approach takes less than a 1/10 of a second.

Use dplyr::tbl_sum() to get formatted database string

---

pkgdown/_pkgdown.yml

Preview: https://dm.pat-s.me/dev/index.html
NB: @krlmlr Please call `tic::use_ghactions_deploy()` to add a valid SSH key for pkgdown deployment (I can't).
Currently the site is build but not deployed, due to the [lack of this key](https://github.com/krlmlr/dm/runs/711756856#step:23:18). 
PS: Would this be a good time to move the repo to the "cynkra" org, now that cynkratemplate is used?
PPS:
Topics missing from index: 
* rows-db
* rows
* rows_truncate

pkgdown: use cynkratemplate

---

.github/workflows/tic.yml

As discussed in https://github.com/krlmlr/dm/issues/374#issuecomment-640413457.
Using a custom GitHub PAT (scopeless) as a secret instead of the default `GITHUB_TOKEN` secrets bumps the rate from 1000 to 5000: https://github.com/krlmlr/dm/runs/748994181?check_suite_focus=true#step:18:95

GHA: Use a custom PAT to increase rate limit

---

.github/workflows/tic.yml

and update caching action version.
gfortran 8.2 (CRAN default) is meanwhile also installed upstream by r-lib/actions.

GHA: Remove `ccache` parts from tic.yml

---

.github/workflows/tic.yml

once rmarkdown > 2.2 is on CRAN.
This reverts commit 6757da59c2c7fac21b8d2cb27ec8943bbe1e8948.

Revert "Avoid testing on R < 3.6 due to known rmarkdown bug"

---

.github/workflows/tic.yml
R/db-interface.R
tests/testthat/test-db-interface.R

in `copy_dm_to()`.
Closes #397.
Closes #395.

Better error message for bad table_names, forbid local target in copy_dm_to

---

R/dm.R
R/format.R
R/nest.R
R/zzx-deprecated.R
man/dm.Rd
tests/testthat/helper-config-db.R
tests/testthat/helper-skip.R
tests/testthat/helper-src.R
tests/testthat/out/bind.txt
tests/testthat/out/output.txt
tests/testthat/test-dm.R
tests/testthat/test-format.R
tests/testthat/test-zzx-deprecated.R

- `dm` objects with local data sources no longer show the "Table source" part in the output.
Closes #394.

dm_get_src() returns NULL for local data sources

---

vignettes/tech-dm-draw.Rmd

Following the discussion in issue `Add feature to write dm_draw #481` a good solution for export of a drawing could be `svg`.

Add hint for export to svg to draw-vignette (Closes #481)

---

R/db-helpers.R
R/db-interface.R

Until https://github.com/r-dbi/DBI/pull/351 becomes available in dbplyr.

Use hack to create compound primary keys

---

R/testthat-wrappers.R
tests/testthat/test-dplyr.R
tests/testthat/test-flatten.R
tests/testthat/test-testthat-wrappers.R
tests/testthat/test-zzx-deprecated.R

closes #566
We build wrappers by replacing the tunneled argument `{{object}}` with `obj <- rlang::eval_tidy({{object}})`, this way we don't execute object 2 times, as we would if we'd just have `object` as the last call of these functions.
We add a simple test for each of these wrappers.
We replace some instances of `expect_message` and `expect_warning` by their counterpart, so relevant tests are now passed.

Issue 566 testthat wrappers

---

R/rows-dm.R
R/rows-truncate.R

to avoid warning on unused argument.

rows_truncate_()

---

vignettes/howto-dm-df.Rmd

Fixed typo.
How can we ensure, that for the vignette used on CRAN the package {nycflights13} is available?
closes #601

fix howto-dm-df vignette

---

R/rows-db.R

Combine `sql_rows_update_prep()` and `sql_rows_patch_prep()` into a single function.
Note that Maria DB used the non-existing field `target_columns_qual_qq`. Maybe you want to add MariaDB to the workflows?

Refactor `sql_rows_prep()`

---

R/dm.R
tests/testthat/test-zoom.R

closes #626
This is a small fix for a very interesting error!
In fact the error we see in linked issue is not one, it's just a message, and it's sent by RStudio, not base R.
Here's a minimal reproduction of the issue :
```
length.foo = function(x) stop("error!")
registerS3method("length", "foo", length.foo)
foo <- 1
attributes(foo) <- list(class = "foo")
#> Error in length.foo(obj) : error!
foo
#> [1] 1
#> attr(,"class")
#> [1] "foo"
```
As we see, the `foo`object was properly created and modified, but the fact that the length method fails makes RStudio display the problematic message.
The guilty function is `.rs.describeObject`, it seems to be called after an object is created or modified in the console, and it calls `length()`.
In our case we have ` length()` --> `length.zoomed_dm()` …

Fix db_get_zoom() to support zooming on empty tables

---

R/disambiguate.R
tests/testthat/_snaps/disambiguate.md
tests/testthat/_snaps/dplyr.md
tests/testthat/test-flatten.R

Closes #684 
We tried to be consistent with `dm_rm_fk()`
``` r
library(dm, warn.conflicts = FALSE)
dm_nycflights13() %>% 
dm_disambiguate_cols()
#> Renaming ambiguous columns: %>%
#>   dm_rename(airlines, airlines.name = name) %>%
#>   dm_rename(airports, airports.name = name) %>%
#>   dm_rename(flights, flights.year = year) %>%
#>   dm_rename(flights, flights.month = month) %>%
#>   dm_rename(flights, flights.day = day) %>%
#>   dm_rename(flights, flights.hour = hour) %>%
#>   dm_rename(planes, planes.year = year) %>%
#>   dm_rename(weather, weather.year = year) %>%
#>   dm_rename(weather, weather.month = month) %>%
#>   dm_rename(weather, weather.day = day) %>%
#>   dm_rename(weather, weather.hour = hour)
#> ── Metadata ──────────────────────────────────────────────────────────────────── …
```

Print code in `dm_disambiguate_cols()`

---

R/disambiguate.R

closes #662 
We add an argument `exclude_pk = TRUE` to `get_table_colnames()` and we set it to `TRUE` in `dm_disambiguate_cols_impl()`.
`get_table_colnames()` is called also in `prepare_dm_for_flatten()` and there it keeps the default behaviour.
``` r
library(dm, warn.conflicts = FALSE)
library(tidyverse)
person  <- tibble(id = 1, person = "Joe")
hobby   <- tibble(id = c(1,1), hobby = c("R Programming", "Basketball"))
country <- tibble(id = 1, place = "Switzerland")
city    <- tibble(country_id = c(1,1), city = c("Zurich", "Geneva"))
dm <-
dm(person, hobby, country, city) %>%
dm_add_pk(person, id) %>%
dm_add_pk(country, id) %>%
dm_add_fk(hobby, id, person, id) %>% 
dm_add_fk(city, country_id, country, id)
dm <- dm_disambiguate_cols(dm)
#> Renamed columns:
#> * id -> person.id, hobby.id, …
```

662 always disambiguate col names

---

R/error-helpers.R
R/global.R
R/schema.R
man/dplyr_table_manipulation.Rd
tests/testthat/_snaps/error-helpers.md
tests/testthat/test-error-helpers.R
tests/testthat/test-schema.R

partly addresses #672: the proactive checks for schema existence are abolished.
For listing schemas on MSSQL we also now avoid matching `schema owner id` to `user id`. I just ran into trouble here (`schema owner id` didn't exist in `user id` list and therefore schema wasn't listed, even though it existed). 
Now used 3054912 as a workaround, that schemas that exist by default for backward compatibility are filtered out.

no proactive checks for schema existence and tweak MSSQL-schema-code

---

R/new_ticker.R

Why was it set to 60 @moodymudskipper @TSchiefer?

Use default width for progress bar

---

R/flatten.R
man/dm_flatten_to_tbl.Rd
vignettes/howto-dm-db.Rmd
vignettes/tech-dm-class.Rmd
vignettes/tech-dm-join.Rmd

close https://github.com/cynkra/dm/issues/999
I have found many other calls to those functions but I decided to leave them - here goes my explanation:
- `dm_get_src()`
- `R/` - only deprecated function itself
- `scratch` - I have left your notes untouched
- `tests/` - as you soft-deprecated then that means that you still expect it to work - would be good to keep that check
- `tbl()`
- I left `demo/` directory as it is as I assume it's for demoes that already happened so this code is unlikely to be executed again. If yes - should be done on the current version at that point in time.
- `R/` - only comments and deprecated function itself
- `tests/` - same as above
- `src_tbls()`
- `demo/` - as above
- I think that the last occurence is intended to call `dplyr::src_tbls` (would be good to …

remove soft deprecated dplyr-src funs

---

R/disentangle.R
R/validate.R
tests/testthat/test-pack_join.R
tests/testthat/test-validate.R

NULL appears in `def$fks`, need to avoid, otherwise something like this fails (and in general no valid dm is produced):
```
dm_disentangle(dm_nycflights13(cycle = TRUE), flights) %>% 
dm_select_tbl(-`airports-1`)
```

FIX: avoid NULL if no fks after disentangle

---

pkgdown/_pkgdown.yml

- bigger font
- search
IMHO #1064 should come after cynkratemplate itself uses BS5 and therefore has a search bar.

docs: BS5 for greater readability

---

R/meta.R

Hopefully consistent across many databases?
MySQL/MariaDB and duckdb work! (`dm_ptype()` gets a zero-row version of the dm as data frames, this wouldn't work if the tables didn't have the necessary columns.)
``` r
library(dm)
con <- DBI::dbConnect(duckdb::duckdb())
dm:::dm_meta(con, simple = TRUE) %>%
dm_ptype()
#> ── Metadata ────────────────────────────────────────────────────────────────────
#> Tables: `schemata`, `tables`, `columns`
#> Columns: 14
#> Primary keys: 3
#> Foreign keys: 2
```
<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

FEAT: New `simple` argument to `dm_meta()`

---

pkgdown/_pkgdown.yml

I think this is tidier and also future-proof.
For example, #1119 added `nest_join.zoomed_dm` and `pack_join.zoomed_dm`, but they are currently missing from the reference index. But, with the current selection helper approach, this wouldn't happen since it would pick up all functions with the pattern ".zoomed_dm$".

docs: Use selection helpers in `_pkgdown.yml`

---

tests/testthat/_snaps/enum-ops.md
tests/testthat/test-enum-ops.R

Cf. #1155, #1154.
This adds the missing snapshot test of `enum_ops()`, prior to its simplification #1162.

Add scratch/code_generation_middleware_2.R to snapshot tests

---

R/enum_ops.R
tests/testthat/_snaps/enum-ops.md
tests/testthat/test-enum-ops.R

#1162 introduced a regression: it produced incorrect `dm_add_pk()` calls for compound primary keys, e.g., `dm_add_pk(., table, col1, col2)` instead of `dm_add_pk(., table, c(col1, col2))`.

Fix regression: compound columns must be grouped with c()

---

R/meta.R
tests/testthat/_snaps/learn.md
tests/testthat/test-learn.R

Fix #1168
The branch name says it all. :sweat_smile: 
I'll add a test, leaving this as draft while I add it. (tested interactively)
``` r
library(RMariaDB)
my_db <- dbConnect(
MariaDB(),
username = "guest",
password = "relational",
dbname = "Financial_ijs",
host = "relational.fit.cvut.cz"
)
library("dm")
#> 
#> Attachement du package : 'dm'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter
my_dm <- dm_from_con(my_db)
#> Keys queried successfully, use `learn_keys = TRUE` to mute this message.
```
<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

fix: mariaDB key guessing in financial example

---

R/key-helpers.R

closes #1151
Using `vctrs::vec_duplicate_any()` when `.data` is a local data frame makes `check_key()` much faster.
``` r
library(bench)
suppressMessages(library(dm))
#> Warning: package 'dm' was built under R version 4.1.2
set.seed(1)
n <- 1e6
df <- replicate(4, sample(n*.9, n, TRUE), simplify = FALSE) %>%
setNames(letters[seq_along(.)]) %>%
tibble::as_tibble()
check_key(df, a, b)
#> Error in `abort_not_unique_key()`:
#> ! (`a`, `b`) not a unique key of `df`.
mark(ck = try(check_key(df, a, b), silent = TRUE))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 ck            10.2s    10.2s    0.0984 …
```

feat: `check_key()` uses `vctrs::vec_duplicate_any()` on local data frames for speed

---

R/key-helpers.R

It looks like you can use `vctrs::vec_count()` to get the same output as `safe_count()` for local data frames much faster. This speeds up `enum_pk_candidates()`
``` r
library(bench)
suppressMessages(library(dm))
#> Warning: package 'dm' was built under R version 4.1.2
suppressMessages(devtools::load_all('~/Documents/GitHub/dm')) # loaded as dm_pr
set.seed(1)
n <- 1e6
sample_out_of <- 4e11
df <- replicate(4, sample(sample_out_of, n, TRUE), simplify = FALSE) %>%
setNames(letters[seq_along(.)]) %>%
tibble::as_tibble() %>%
mutate(a = replace(a, 1:4, NA))
dm_pr::enum_pk_candidates(df)
#> # A tibble: 4 × 3
#>   columns candidate why                                                         
#>   <keys>  <lgl>     <chr>                                                       
#> 1 d       TRUE …
```

feat: `is_unique_key()`uses `vctrs::vec_count()` on local data frames for speed

---

R/primary-keys.R
man/dm_get_all_pks.Rd

man page says the output tibble contains a column `pk_cols`, but currently it's `pk_col`.
I didn't update the snapshots, since my package setup differs slightly from what is needed to produce the "correct" snapshots, so tests will fail initially.

docs: Fix column names in `?dm_get_all_pks`

---

R/pack_join.R

Sort packed columns in original order. 
Closes #1513

feat: `pack_join(keep = TRUE)` preserves order of packed columns

---

.github/workflows/validate.yaml

tests were run twice in a row in the same manner, if I am not mistaken.

remove duplicate step in validate GHA

---

R/gui-gui_global.R
tests/testthat/test-validate.R
tests/testthat/test-zoom.R

This PR makes your package compatible with the next version of dplyr:
- `if_else()` now uses vctrs, which generally makes it more permissive when there are varying types, but it also means that the inputs must always be vectors. In dm's case, `NULL` was being used as the missing type for lists, when really `list(NULL)` needs to be used for vctrs
In dev dplyr, you could also just use `NA` now but that won't work with CRAN dplyr.
We plan to submit dplyr 1.1.0 on January 27th.
This should be compatible with both dev and CRAN dplyr. It would help us out if you could go ahead and send a patch version of your package in ahead of time! Thanks!
---
Also, I think if you try and check this against dev dplyr right now then you'll see an additional failure related to `left_join()` and unused …

chore: Use correctly typed missing value for lists

---

R/build_copy_queries.R
R/db-helpers.R
tests/testthat/_snaps/autoincrement.md
tests/testthat/helper-src.R
tests/testthat/test-autoincrement.R
tests/testthat/test-db-interface.R

on SQLite, SQL Server, Postgres
code mostly taken from https://github.com/cynkra/dm/pull/1654

feat: support AI PKs for dm_copy_to() for empty tables (ptype)

---

R/foreign-keys.R
R/primary-keys.R
man/dm_get_all_fks.Rd
man/dm_get_all_pks.Rd
tests/testthat/test-foreign-keys.R
tests/testthat/test-primary-keys.R

feat: `dm_get_all_pks()` and `dm_get_all_fks()` keep order of `table` or `parent_table` argument

---

R/validate.R
tests/testthat/test-validate.R

since dbplyr::copy_inline() produces such tables.
closes #1695

Chore: accept dm tables that are tbl_sql but not tbl_dbi

---

R/dm_unnest_tbl.R

Otherwise in the future, there will be an additional unique key, which is the same as the then added PK.

chore: `dm_unpack_tbl()` sets PK before FK

---

R/foreign-keys.R
R/primary-keys.R
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/test-foreign-keys.R
tests/testthat/test-primary-keys.R

...and produce a nicer error for `dm_get_all_fks(parent_table = "<something_wrong>")`
currently:
``` r
suppressMessages(devtools::load_all("~/git/cynkra/dm"))
dm_nycflights13() %>% 
dm_get_all_pks("timetable")
#> Error in paste0("Table not in dm object: ", parent_table[which(is.na(idx))[[1]]]): object 'parent_table' not found
```
<sup>Created on 2023-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

fix: Correct error message if nonexisting table is passed to `dm_get_all_pks()`

---

tests/testthat/test-flatten.R

We are preparing to release dplyr 1.1.1 and dm popped up in the revdep checks.
We realized that we didn't get the `multiple` argument quite right the first time around 😞 . It was too aggressive since it warned on both one-to-many and many-to-many joins. In 1.1.1 we've made two improvements:
- `multiple` now defaults to `"all"`. The options of `NULL`, `"error"`, and `"warning"` are deprecated.
- `relationship` is a new argument to add known constraints onto the join procedure, such as `"many-to-one"`, which replaces `multiple = "error"`.
The default of `relationship` checks to see if there is a `many-to-many` relationship between the keys of `x` and `y` and will warn if one is present. This should be _much_ rarer than what we checked for before, and targets the most dangerous case that we …

chore: Minimal patch to fix multiple match updates

---

DESCRIPTION

chore: require purrr >= 1.0.0 for `list_c()`

---

inst/cheatsheet.css

Old URLs use the s3 bucket's url directly. The new URLs will benefit from the cloudfront and also free some redundant resources.

change fonts url to cynkra.com

---

R/rows-dm.R

After dbplyr needed a hot patch release, the check on the package version didn't work anymore.
This now checks the interface instead of the package version.

chore: Establish compatibility with dbplyr 2.3.3 and 2.4.0

---

R/draw-dm.R
man/dm_draw.Rd

list of possible elements for argument `font_size` was not properly rendered in the docs

docs: Add information on default font size to `?dm_draw`

---

R/dplyr.R
R/select-tbl.R
R/utils.R

Using superseded functions harms the performance quite a bit.
I noticed this when removing tables via `dm::dm_select_tbl(dm, -any_of(tables_to_remove))`.
```r
data <- nycflights_subset()
flights <- data$flights
weather <- data$weather
airlines <- data$airlines
airports <- data$airports
planes <- data$planes
dm <- dm(airlines, airports, flights, planes, weather)
remove_tables <- function() {
dm %>% 
dm_select_tbl(-airlines) %>% 
dm_select_tbl(-airports) %>% 
dm_select_tbl(-flights) %>% 
dm_select_tbl(-planes) %>% 
dm_select_tbl(-weather)
}
bench::mark(
remove_tables()
)
```

perf: Replace superseded `dplyr::recode()`

---

R/dm.R
R/utils.R

There are other places where `tibble()` is used. It might be worth looking into them as well.
```r
data <- nycflights_subset()
flights <- data$flights
weather <- data$weather
airlines <- data$airlines
airports <- data$airports
planes <- data$planes
dm <- dm(airlines, airports, flights, planes, weather)
add_keys <- function() {
dm %>% 
dm_add_pk(planes, tailnum) %>%
dm_add_pk(airlines, carrier) %>%
dm_add_pk(airports, faa) %>%
dm_add_fk(flights, tailnum, planes) %>%
dm_add_fk(flights, carrier, airlines) %>%
dm_add_fk(flights, origin, airports)
}
for (i in 1:100) {
dm_nycflights13()
}
bench::mark(
add_keys()
)
```

perf: Replace `tibble()` by `fast_tibble()`

---

R/db-interface.R
man/copy_dm_to.Rd

docs: Deprecate `copy_dm_to(copy_to = )` argument

---

R/build_copy_queries.R
R/flatten.R
R/table-surgery.R
tests/testthat/_snaps/code-generation.md
tests/testthat/test-code-generation.R

chore: Prepare for removal of magrittr imports

---

tests/testthat/_snaps/dm.md
tests/testthat/_snaps/examine-cardinalities.md
tests/testthat/_snaps/examine-constraints.md
tests/testthat/test-dm.R
tests/testthat/test-examine-cardinalities.R
tests/testthat/test-examine-constraints.R

Why do these get auto-removed?

chore: Snapshots

---

R/check_suggested.R
R/nycflights13.R
man/dm_nycflights13.Rd
tests/testthat/_snaps/check_suggested.md
tests/testthat/test-check_suggested.R

Addresses #1735, closes #2035.
Briefly, it uses `check_installed()` in the check_suggested function to make it easier to install DiagrammeR. I guess `check_suggests()` could be simplified further. (and get the function by chaining rather than naming.
Mind the small tweak in tests to avoid skipping the test. We have to make it believe that we are not testing to avoid skipping the test. and actually record the message.
Note that check_installed()` errors in non-interactive sessions.
In an unrelated way, I added a link to the data frame vignette in the dm_nyc13 flights as I had issues to get started and this vignette helped me.

chore: Improve handling of suggested packages, add link in doc

---

R/dm.R
R/globals.R
R/validate.R

perf: Speed up `dm()`, `new_dm()`, `as_dm()` and `dm_validate()`. `dm()` and `as_dm()` no longer call `dm_validate()`

---

R/dm.R
man/materialize.Rd
tests/testthat/_snaps/dm.md
tests/testthat/test-dm.R

Documented workflow for persistent tables.
Closes #2059.

feat: Explicitly fail on `compute(temporary = TRUE)`, which never worked correctly

---

tests/testthat/test-db-interface.R

test: Add test for `copy_dm_to(table_names = )`

---

DESCRIPTION
tests/testthat/helper-src.R
tests/testthat/test-db-interface.R

Small PR to drop mockr in favour of `local_mocked_bindings()` and crayon in favour of cli.
relates to #365

chore: Drop crayon and mockr dependencies

---

.github/workflows/R-CMD-check-status.yaml
.github/workflows/R-CMD-check.yaml
.github/workflows/custom/before-install/action.yml
.github/workflows/fledge.yaml
.github/workflows/install/action.yml
.github/workflows/lock.yaml
.github/workflows/pkgdown.yaml
DESCRIPTION
NEWS.md
R/db-helpers.R
cran-comments.md

Found the following Rd file(s) with Rd \link{} targets missing package
anchors:
dm_examine_cardinalities.Rd: as_tibble
dm_examine_constraints.Rd: as_tibble
dm_from_con.Rd: src
dm_zoom_to.Rd: nest_join
json_nest.Rd: tidyr_tidy_select
json_pack.Rd: tidyr_tidy_select
Please provide package anchors for all Rd \link{} targets not in the
package itself and the base packages.
Running ‘testthat.R’ [154s/81s]
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
> library(testthat)
> 
> # Need to use qualified call, this is checked in helper-print.R
> testthat::test_check("dm")
Loading required package: dm
Attaching package: 'dm'
The following object is masked from 'package:stats':
filter
Starting 2 test processes
[ FAIL 1 | WARN 0 | SKIP 242 | PASS 1355 ]
══ Skipped tests (242) …

fledge: CRAN release v1.0.11
