README.Rmd

@JohnMount: Is this an accurate description?

Add rquery paragraph

---

vignettes/setting_up_dm.Rmd

Adds setup article to pkdown site from gitlab. Already adjusted for newest version.

Add setup documentation

---

R/graph.R
tests/testthat/test-graph.R

Had a bug in the function, that would lead to problems, once we have cycles.

fix function 'create_graph_from_dm()'

---

R/draw-dm.R
man/cdm_draw.Rd

- fix bug in documentation of `cdm_draw()`
closes #19

fix doc of 'cdm_draw()'

---

R/dm.R
R/error-helpers.R

better error description in case of numeric subsetting

---

README.Rmd
README.md

Great to see projects aiming for data warehousing concepts in R!
Adding related project to list of mentioned works in that field so far.

mention related work in README

---

R/disambiguate.R
man/cdm_disambiguate_cols.Rd
tests/testthat/helper-src.R

issues from f-disambiguate

---

R/foreign-keys.R
R/primary-keys.R
man/cdm_enum_fk_candidates.Rd
tests/testthat/helper-src.R
tests/testthat/test-foreign-key-functions.R

- checks now for class compatibility
- if compatible, checks if subset
- lists in column `why`:
1. nothing if candidate
1. class `...` doesn't match pk-col class `...`
1. following values are not in pk-col: ...
fixes #24

detailed 'cdm_enum_fk_candidates()'

---

R/primary-keys.R
vignettes/dm-introduction-relational-data-models.Rmd

add library call to vignette

---

R/filter-dm.R
R/filter-helpers.R
man/cdm_filter.Rd
vignettes/dm-filtering.Rmd

- update doc of `cdm_filter()`
- update vignette "Filtering in Relational Data Models"
fixes #70

Define filtering operation

---

R/error-helpers.R
R/flatten.R
man/cdm_flatten_to_tbl.Rd
tests/testthat/test-flatten.R

- support select helpers, deselecting
- tests
fixes #101

support {tidyselect} for flatten/squash

---

R/select-tbl.R
tests/testthat/test-select-tbl.R

- order in selection -> order of tables in `dm`

reorder tables in 'dm' using 'cdm_select_tbl()' 

---

R/dplyr.R
R/filter-helpers.R
tests/testthat/test-dplyr.R

Use disambiguation for joins

---

vignettes/setting_up_dm.Rmd

This is a dummy-update to test gh pipeline

Test update to setting_up_dm

---

R/add-tbl.R
R/check-cardinalities.R
R/dm.R
R/select-tbl.R

Incomplete, other files need to be checked as well.

Some full stops added to params

---

vignettes/dm-zoom-to-table.Rmd

Roughly formulated, needs to be refined
addresses #171 (does not completely fix it)

zoom vignette

---

R/dm.R
R/error-helpers.R
R/test-dm.R
tests/testthat/test-dm.R

- more checks
- all problems found in this function raise an error of class `cdm_error_full("dm_invalid")`
closes #69

extended 'validate_dm'

---

R/disambiguate.R
R/foreign-keys.R

Please check.
Closes #165.
Closes #167.

Fixes for issues #165 and #167

---

R/table-surgery.R
tests/testthat/test-table-surgery.R

tidyselect for 'decompose_table()'

---

R/key-helpers.R
tests/testthat/test-check-key.R

...since we were already bragging about that in the documentation

'check_key()' with {tidyselect}

---

R/key-helpers.R
man/check_key.Rd

update doc and tweak implementation of 'check_key()'

---

vignettes/wip/dm-version-migration-guide.Rmd

when updating {dm} from version <= 0.0.5 to a version >= 0.0.6
closes #234

migration guide

---

vignettes/dm-filtering.Rmd
vignettes/dm.Rmd

- changed default behavior of `dm_nycflights13()` (`flights` subset)
- tweaks

slight vignette update

---

vignettes/dm-version-migration-guide.Rmd

after #309 it would also likely result in a bug

fix vignette label

---

.Rbuildignore
Makefile
tests/testthat/helper-config-db.R
tests/testthat/helper-skip.R
tests/testthat/helper-src.R
tests/testthat/test-dm.R
tests/testthat/test-nest.R

Test multiple sources

---

tests/testthat/helper-src.R
tests/testthat/test-dm.R
tests/testthat/test-dplyr.R
tests/testthat/test-filter-dm.R
tests/testthat/test-format.R
tests/testthat/test-key-helpers.R
tests/testthat/test-table-surgery.R
tests/testthat/test-tidyr.R
tests/testthat/test-utils.R
tests/testthat/test-zzx-deprecated.R

WIP: Skip tests that fail on other sources

---

DESCRIPTION
R/format.R
tests/testthat/helper-skip.R
tests/testthat/helper-src.R
tests/testthat/out/commas.txt
tests/testthat/test-dm.R
tests/testthat/test-dplyr.R
tests/testthat/test-draw-dm.R
tests/testthat/test-examine-constraints.R
tests/testthat/test-filter-dm.R
tests/testthat/test-flatten.R
tests/testthat/test-format.R
tests/testthat/test-key-helpers.R
tests/testthat/test-nest.R
tests/testthat/test-select-tbl.R
tests/testthat/test-table-surgery.R
tests/testthat/test-tidyr.R
tests/testthat/test-zoom.R
tests/testthat/test-zzx-deprecated.R

reenable tests on SQL Server

---

.github/workflows/main.yml

GHA: only require LaTeX in one run

---

.github/workflows/main.yml

GHA: Test on R 3.3

---

.Rbuildignore
.github/workflows/main.yml

Blocked by https://github.com/ropensci/tic/pull/254

GHA: Run on Windows

---

R/dm.R
tests/testthat/out/output.txt
tests/testthat/test-dm.R

printing of empty dm

---

R/rows-db.R
R/rows-dm.R
man/rows-db.Rd
man/rows-dm.Rd

- agreed doc updates
- two types of FIXMEs

update documentation after #319

---

R/dm.R
R/dplyr.R
R/error-helpers.R
R/filter-dm.R
R/flatten.R
R/foreign-keys.R
R/graph.R
R/primary-keys.R
R/select-tbl.R
R/select.R
R/test-dm.R
R/zoom.R
R/zzx-deprecated.R
tests/testthat/out/error-msgs.txt
tests/testthat/test-error-helpers.R
tests/testthat/test-filter-dm.R

Better error message for missing unquoted arguments

---

DESCRIPTION
R/tidyselect.R
tests/testthat/out/tidyselect.txt
tests/testthat/test-tidyselect.R

Mention tables in error messages

---

.github/odbc/odbcinst.ini
.github/workflows/db-mssql.yml

Fix MSSQL tests

---

.github/workflows/tic.yml
R/error-helpers.R
R/key-helpers.R
tests/testthat/out/card-0-n-data_card_1-data_card_2.txt
tests/testthat/out/check-if-subset-2a-1a.txt
tests/testthat/out/check-set-equality-1a-2a.txt
tests/testthat/out/code_from_paste.txt
tests/testthat/out/error-msgs.txt
tests/testthat/out/examine-constraints-as-tibble.txt
tests/testthat/test-paste.R

Fix test output

---

vignettes/howto-dm-copy.Rmd
vignettes/howto-dm-db.Rmd
vignettes/howto-dm-df.Rmd
vignettes/howto-dm-rows.Rmd

@krlmlr howto-rows, db, df and copy each had tiny typos in them.

fixed small typos

---

NEWS.md
README.Rmd
README.md
cran-comments.md
pkgdown/_pkgdown.yml

CRAN release v0.1.8

---

.github/workflows/db-postgres.yml
DESCRIPTION

Move RPostgres to Enhances

---

.github/workflows/db-postgres.yml
DESCRIPTION
NEWS.md
cran-comments.md

CRAN release v0.1.9

---

.github/workflows/db-mssql.yml
.github/workflows/db-postgres.yml
.github/workflows/db-sqlite.yml
.github/workflows/tic.yml

{tic} templates can be updated :rocket: :robot:

Update tic templates [ci-skip]

---

DESCRIPTION
NEWS.md
R/key-helpers.R
R/primary-keys.R
README.Rmd
README.md
cran-comments.md
pkgdown/_pkgdown.yml
tests/testthat/helper-src.R
tests/testthat/test-primary-keys.R

CRAN release v0.1.10

---

vignettes/tech-dm-zoom.Rmd

The first paragraph is rendered incorrectly, also it's a bit bumpy as an intro.
CC @jawond.

Bullet points, and rewrite intro

---

vignettes/howto-dm-theory.Rmd

so that it closer matches the defined behavior.
CC @jawond.

Rewrite section on referential integrity

---

NEWS.md
README.Rmd
README.md
cran-comments.md

CRAN release v0.1.11

---

NEWS.md
cran-comments.md

CRAN release v0.1.12

---

tests/testthat/test-dm.R

Needs https://github.com/tidyverse/dbplyr/pull/649.

Skip compute() tests

---

.github/workflows/db-mssql.yaml
.github/workflows/db-postgres.yaml
.github/workflows/db-sqlite.yaml
tests/testthat/test-dm.R

Sync database workflows

---

vignettes/howto-dm-copy.Rmd
vignettes/setup/setup.R
vignettes/tech-dm-filter.Rmd

Don't build vignettes in R CMD check

---

vignettes/howto-dm-copy.Rmd
vignettes/howto-dm-db.Rmd
vignettes/howto-dm-df.Rmd
vignettes/howto-dm-rows.Rmd
vignettes/howto-dm-theory.Rmd
vignettes/tech-dm-cdm.Rmd
vignettes/tech-dm-class.Rmd
vignettes/tech-dm-draw.Rmd
vignettes/tech-dm-filter.Rmd
vignettes/tech-dm-join.Rmd
vignettes/tech-dm-low-level.Rmd
vignettes/tech-dm-naming.Rmd
vignettes/tech-dm-zoom.Rmd
vignettes/wip/dm-insert.Rmd
vignettes/wip/dm-readme-old.Rmd
vignettes/wip/dm-shiny-dynafilter.Rmd
vignettes/wip/dm-tips-and-tricks.Rmd

Remove space at EOL in vignettes

---

R/db-helpers.R
tests/testthat/test-db-helpers.R
tests/testthat/test-disambiguate.R
tests/testthat/test-dplyr.R
tests/testthat/test-draw-dm.R
tests/testthat/test-examine-constraints.R
tests/testthat/test-select-tbl.R
tests/testthat/test-zoom.R

Enable Postgres tests

---

DESCRIPTION
R/error-helpers.R
R/foreign-keys.R
R/primary-keys.R
README.Rmd
README.md
man/dm_add_fk.Rd
man/dm_add_pk.Rd
man/dm_get_all_fks.Rd
man/dm_get_all_pks.Rd
man/dm_get_fk.Rd
man/dm_get_pk.Rd
pkgdown/_pkgdown.yml
vignettes/howto-dm-db.Rmd
vignettes/howto-dm-df.Rmd
vignettes/howto-dm-theory.Rmd
vignettes/out/dm-readme-old.md
vignettes/out/howto-dm-db.md
vignettes/out/howto-dm-df.md
vignettes/out/howto-dm-theory.md
vignettes/out/tech-dm-filter.md
vignettes/out/tech-dm-join.md
vignettes/out/tech-dm-naming.md
vignettes/tech-dm-filter.Rmd
vignettes/tech-dm-join.Rmd
vignettes/tech-dm-naming.Rmd
vignettes/wip/dm-readme-old.Rmd

krlmlr -> cynkra

---

DESCRIPTION
NEWS.md
cran-comments.md
vignettes/howto-dm-df.Rmd
vignettes/howto-dm-theory.Rmd
vignettes/tech-dm-filter.Rmd
vignettes/tech-dm-join.Rmd

CRAN release v0.1.13

---

R/zoom.R

Faster flattening

---

R/zoom.R
R/zzx-deprecated.R

Faster dm_update_zoomed()

---

R/db-helpers.R

One-column primary keys are created again

---

R/foreign-keys.R
R/primary-keys.R
man/dm_add_fk.Rd
man/dm_add_pk.Rd
man/dm_enum_fk_candidates.Rd
man/dm_get_all_fks.Rd
man/dm_get_all_pks.Rd
man/dm_get_fk.Rd
man/dm_get_pk.Rd
man/dm_has_fk.Rd
man/dm_has_pk.Rd
man/enum_pk_candidates.Rd

Add ellipsis arguments to functions

---

R/dm.R

Versioned class for dm objects

---

R/db-helpers.R
R/db-interface.R
R/dm-from-src.R
R/error-helpers.R
R/learn.R
man/copy_dm_to.Rd
man/dm_from_src.Rd
tests/testthat/_snaps/error-helpers.md
tests/testthat/test-error-helpers.R

Support schema on MariaDB in dm_from_src()

---

pkgdown/_pkgdown.yml

Reorganize references

---

tests/testthat/helper-src.R

Use output from copy_to()

---

R/add-tbl.R
R/db-helpers.R
R/db-interface.R
R/dm-from-src.R
R/dm.R
R/draw-dm.R
R/paste.R
R/rows-dm.R
tests/testthat/test-add-tbl.R
tests/testthat/test-db-helpers.R
tests/testthat/test-db-interface.R
tests/testthat/test-dm-from-src.R
tests/testthat/test-dm.R

src_tbls() -> src_tbls_impl()

---

scratch/dm-overview.Rmd
vignettes/howto-dm-db.Rmd
vignettes/howto-dm-df.Rmd
vignettes/howto-dm-theory.Rmd
vignettes/tech-dm-class.Rmd

Compound keys now supported

---

NEWS.md
cran-comments.md

CRAN release v0.2.0

---

R/foreign-keys.R
R/primary-keys.R
R/zzx-deprecated.R
tests/testthat/_snaps/rows-dm.md
tests/testthat/test-dm.R
tests/testthat/test-dplyr-src.R
tests/testthat/test-filter-dm.R
tests/testthat/test-rows-dm.R
tests/testthat/test-zoom.R

Should have been an error in v0.2.0 already.

check_dots_empty() in pk and fk functions

---

tests/testthat/_snaps/draw-dm.md
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/select.md
tests/testthat/test-dm.R
tests/testthat/test-draw-dm.R
tests/testthat/test-foreign-keys.R
tests/testthat/test-select.R
tests/testthat/test-tidyr.R

Prefer snapshot tests

---

DESCRIPTION
tests/testthat/_snaps/filter-dm.md
tests/testthat/_snaps/zzx-deprecated.md
tests/testthat/helper-expectations.R
tests/testthat/helper-src.R
tests/testthat/test-filter-dm.R
tests/testthat/test-zzx-deprecated.R

Prefer snapshot testing

---

R/add-tbl.R
R/dm.R
R/dplyr.R
R/filter-dm.R
R/zoom.R
R/zzx-deprecated.R

Refactor zooming

---

R/foreign-keys.R

Simplify dm_get_all_fks_impl()

---

R/dm.R
R/upgrade.R

to avoid paying for every S3 dispatch.

Avoid versioning dm objects in class, use dedicated attribute

---

R/dm.R
R/foreign-keys.R
R/upgrade.R
R/zoom.R
R/zzz.R
tests/testthat/_snaps/dm.md
tests/testthat/test-upgrade.R
tests/testthat/test-validate.R

Add ref_column to data structure

---

R/add-tbl.R
R/dm.R
R/filter-helpers.R
R/zoom.R
R/zzx-deprecated.R
R/zzz.R
TODO.md
tests/testthat/test-dm.R
tests/testthat/test-zoom.R

Satisfy strict checks

---

R/upgrade.R
tests/testthat/helper-src.R
tests/testthat/test-dplyr.R
tests/testthat/test-flatten.R

Tweak tests

---

R/foreign-keys.R
R/primary-keys.R
man/dm_add_fk.Rd
man/dm_add_pk.Rd
man/dm_get_all_fks.Rd
man/dm_get_all_pks.Rd
man/dm_get_fk.Rd
man/dm_get_pk.Rd

Add documentation for compound key syntax

---

R/foreign-keys.R
R/primary-keys.R
man/dm_get_all_fks.Rd
man/dm_get_all_pks.Rd
tests/testthat/_snaps/bind.md
tests/testthat/_snaps/dplyr.md
tests/testthat/_snaps/draw-dm/nycflight-dm-copy.svg
tests/testthat/_snaps/filter-dm.md
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/_snaps/tidyr.md
tests/testthat/helper-zoom.R
tests/testthat/test-dplyr.R
tests/testthat/test-foreign-keys.R
tests/testthat/test-primary-keys.R
tests/testthat/test-tidyr.R

New table args to dm_get_all_?ks(), do not sort fks

---

R/db-helpers.R
R/draw-dm.R
R/examine-constraints.R
R/foreign-keys.R
R/global.R
R/paste.R
R/zoom.R
R/zzx-deprecated.R
TODO.md
man/dm_get_all_fks.Rd
tests/testthat/_snaps/dplyr.md
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/_snaps/select.md
tests/testthat/_snaps/tidyr.md
tests/testthat/_snaps/zoom.md
tests/testthat/test-zzx-deprecated.R
vignettes/out/tech-dm-class.md
vignettes/out/tech-dm-join.md

Rename parent_pk_cols to parent_key_cols

---

R/dm.R
man/dm.Rd
man/dplyr_table_manipulation.Rd
vignettes/dm.Rmd
vignettes/howto-dm-copy.Rmd
vignettes/howto-dm-db.Rmd
vignettes/howto-dm-rows.Rmd

Fix GHA warnings

---

R/rows-dm.R
man/rows-dm.Rd

Added progress bars to `dm_rows_*` functions.
I used an empty label to the pb since `dm_rows_run` is called for different purposes.
if you can think of other functions that need a progress bar, please shoot.

add progress bars to dm_rows_* functions

---

R/db-helpers.R
R/db-interface.R
R/dm.R
man/copy_dm_to.Rd
man/materialize.Rd

to simplify workign with spatial and other nonstandard data.
CC @moodymudskipper. (Can't add you as a reviewer yet, pending invite.)

progress and copy_to arguments to collect() and copy_dm_to()

---

DESCRIPTION
TODO.md
tests/testthat/_snaps/rows-db.md
tests/testthat/_snaps/rows-dm.md
tests/testthat/helper-skip.R
tests/testthat/helper-src.R
tests/testthat/test-db-helpers.R
tests/testthat/test-db-interface.R
tests/testthat/test-dm-from-src.R
tests/testthat/test-dm.R
tests/testthat/test-learn.R
tests/testthat/test-nest.R
tests/testthat/test-rows-db.R
tests/testthat/test-rows-dm.R
tests/testthat/test-select-tbl.R
tests/testthat/test-zzx-deprecated.R

Always run database tests on sqlite for df source

---

R/db-interface.R
man/copy_dm_to.Rd
tests/testthat/_snaps/rows-db.md

- `copy_to` argument
- fix progress bar

Tweak copy_dm_to()

---

NEWS.md
cran-comments.md

CRAN release 0.2.2

---

R/financial.R

Don't check financial examples on CRAN

---

NEWS.md
cran-comments.md

CRAN release v0.2.3

---

R/testthat-wrappers.R
tests/testthat/helper-expectations.R
tests/testthat/test-db-interface.R

Establish compatibility with testthat 3.0.3

---

.github/workflows/validate.yaml
R/dm.R

The workflow is a tweaked copy of the db-sqlite workflow.
Closes #202.

Add validation workflow

---

DESCRIPTION
tests/testthat/_snaps/dm.md
tests/testthat/_snaps/examine-constraints.md

How can we make these tests less brittle?

Update tests for pillar 1.6.2

---

R/error-helpers.R
tests/testthat/_snaps/error-helpers.md

Establish compatibility with rlang > 0.4.11

---

R/rows-db.R

Integrate `sql_rows_upsert_prep()` into `sql_rows_prep()`

---

R/rows-db.R
tests/testthat/_snaps/rows-db.md
tests/testthat/test-rows-db.R

Support `returning` for `in_place = FALSE`

---

NEWS.md
R/financial.R
cran-comments.md
man/dm_financial.Rd
tests/testthat/test-rows-db.R
vignettes/howto-dm-copy.Rmd
vignettes/howto-dm-db.Rmd
vignettes/setup/setup.R
vignettes/tech-dm-join.Rmd

CRAN release v0.2.4

---

DESCRIPTION
R/global.R
R/pixarfilms.R
pkgdown/_pkgdown.yml

Add function to generate pixarfilms dm object

---

R/examine-constraints.R
tests/testthat/_snaps/examine-constraints.md
tests/testthat/_snaps/rows-dm.md

missing ticks in `dm_examine_constraints()`'s output

---

NEWS.md
cran-comments.md

CRAN release v0.2.6

---

.github/workflows/R-CMD-check.yaml
tests/testthat/test-dm-from-src.R

Reenable tests on Windows 3.6

---

R/examine-constraints.R

typo in check_fk_constraints()

---

R/db-interface.R
R/dm-from-src.R
R/error-helpers.R
R/foreign-keys.R
R/paste.R
R/primary-keys.R
R/test-dm.R
R/validate.R
R/zzx-deprecated.R

closes #743 
(oops, misnamed the branch "753")

.subclass -> class

---

R/dm_wrap.R
man/dm_unwrap.Rd
man/dm_wrap.Rd
tests/testthat/test-dm_wrap.R

removed from args, doc, and tests
closes #754

remove `silent` arg

---

DESCRIPTION

from https://github.com/jeroen/jsonlite/pull/374. Upstream: https://github.com/jeroen/jsonlite/issues/373.

Add remote

---

R/dm_unnest_tbl.R
man/dm_unpack_tbl.Rd

Add badge for `dm_unpack_tbl()`

---

R/dm_wrap.R

Remove `dm_wrap_tb_impl()` and move code to `dm_wrap_tbl()`

---

DESCRIPTION
tests/testthat/_snaps/add-tbl.md
tests/testthat/_snaps/bind.md
tests/testthat/_snaps/check_suggested.md
tests/testthat/_snaps/disambiguate.md
tests/testthat/_snaps/dm.md
tests/testthat/_snaps/dm_pixarfilms.md
tests/testthat/_snaps/dplyr.md
tests/testthat/_snaps/error-helpers.md
tests/testthat/_snaps/examine-cardinalities.md
tests/testthat/_snaps/examine-constraints.md
tests/testthat/_snaps/filter-dm.md
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/key-helpers.md
tests/testthat/_snaps/pack_join.md
tests/testthat/_snaps/paste.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/_snaps/rows-db.md
tests/testthat/_snaps/rows-dm.md
tests/testthat/_snaps/select-tbl.md
tests/testthat/_snaps/select.md
tests/testthat/_snaps/tidyselect.md
tests/testthat/_snaps/upgrade.md
tests/testthat/_snaps/waldo.md

This affects how snapshots are generated, and fixes our failures with dev testthat.

Require rlang 1.0.1

---

R/check_suggested.R
R/zzz.R
tests/testthat/_snaps/check_suggested.md

Suggested messages are given only once per session, per message.

check_suggested() is memoised, except for testthat

---

R/validate.R
R/zoom.R
tests/testthat/_snaps/dplyr.md
tests/testthat/test-validate.R

@TSchiefer @moodymudskipper: Can you please finish this?
Closes #856.

Fix column tracking for foreign keys

---

R/zoom.R
tests/testthat/_snaps/draw-dm/nycflight-dm.svg
tests/testthat/test-zoom.R

inherit color from original table for dm_insert_zoomed()

---

R/examine-constraints.R
man/dm_add_tbl.Rd
man/dm_bind.Rd
man/dm_zoom_to.Rd
tests/testthat/_snaps/examine-constraints.md
tests/testthat/test-tidyselect.R

Remove extra spaces when examining constraints with compound keys

---

NEWS.md
cran-comments.md

CRAN release v0.2.8

---

R/financial-db-con.R

Update credentials to databases hosted on pacha.dev

---

R/pack_join.R
man/pack_join.Rd

Move ellipsis
Don't forward dots to left_join
Use check_dots_empty()
Fix documentation of x,y
seealso
example
Closes #920

Harmonize `pack_join()`

---

tests/testthat/helper-print.R

Fix compatibility with dev dbplyr

---

R/dm-from-src.R
R/learn.R
R/postgres.R
tests/testthat/_snaps/bind.md
tests/testthat/_snaps/dm_nest_tbl.md
tests/testthat/_snaps/dm_wrap.md
tests/testthat/_snaps/draw-dm.md
tests/testthat/_snaps/filter-dm.md
tests/testthat/_snaps/paste.md
tests/testthat/_snaps/rows-dm.md
tests/testthat/_snaps/zzx-deprecated.md
tests/testthat/helper-src.R
tests/testthat/test-flatten.R

FIX: Learning for PostgreSQL

---

R/disambiguate.R
R/draw-dm.R
R/examine-constraints.R
R/nycflights13.R
R/pixarfilms.R
man/dm_disambiguate_cols.Rd
man/dm_draw.Rd
man/dm_examine_constraints.Rd
man/dm_nycflights13.Rd
man/dm_pixarfilms.Rd

API: Add ellipses to `dm_disambiguate_cols()`, `dm_draw()`, `dm_examine_constraints()`, `dm_nycflights13()` and `dm_pixarfilms()`

---

R/dm.R
man/dm.Rd

API: `dm()` and related functions are stable

---

R/dm.R
R/zzx-deprecated.R

CHORE: Remove all uses of dm_from_src()

---

R/build_copy_queries.R
R/db-helpers.R
R/test-dm.R
tests/testthat/_snaps/df/db-interface.md
tests/testthat/_snaps/maria/db-interface.md
tests/testthat/_snaps/mssql/db-interface.md
tests/testthat/_snaps/postgres/db-interface.md
tests/testthat/_snaps/sqlite/db-interface.md
tests/testthat/test-db-helpers.R
tests/testthat/test-flatten.R
tests/testthat/test-rows-db.R
tests/testthat/test-rows-dm.R
tests/testthat/test-table-surgery.R

Adding CI/CD tests for MariaDB next.

chore: Fix tests locally for MariaDB

---

vignettes/dm.Rmd
vignettes/howto-dm-db.Rmd

chore: Use fallback db also for vignettes

---

R/code-generation.R
scratch/code_generation_examples.R
tests/testthat/_snaps/code-generation.md
tests/testthat/test-code-generation.R

then I think the script in https://github.com/cynkra/dm/pull/1133 would work with `cg_block <- new_cg_block(quo(dm))`

use eval_tidy() (and expect quo(input_object))

---

R/enum_ops.R
scratch/code_generation_middleware.R
scratch/code_generation_middleware_2.R
scratch/code_generation_middleware_3.R

- Allow selecting table name and column name(s) before selecting operation.
- Distinction between inputs, user choices and outputs.
- Shiny app flow.

More tweaks to middleware

---

vignettes/dm.Rmd
vignettes/howto-dm-df.Rmd
vignettes/howto-dm-rows.Rmd

docs: Consistent captioning in articles

---

R/enum_ops.R

Fix second middleware script

---

.github/workflows/R-CMD-check.yaml
.github/workflows/style/action.yml

chore: Ignore failures to list GHA cache

---

.github/workflows/style/action.yml

chore: Fix styler GHA

---

tests/testthat/_snaps/bind.md
tests/testthat/_snaps/df/db-interface.md
tests/testthat/_snaps/df/meta/columns.csv
tests/testthat/helper-src.R
tests/testthat/test-add-tbl.R
tests/testthat/test-bind.R
tests/testthat/test-db-interface.R
tests/testthat/test-dm.R
tests/testthat/test-dplyr-src.R
tests/testthat/test-nest.R
tests/testthat/test-rows-dm.R
tests/testthat/test-validate.R
tests/testthat/test-zzx-deprecated.R

chore: Switch to duckdb as default database backend

---

R/rows-dm.R
tests/testthat/_snaps/rows-dm.md

docs: better inform message for dm rows (#414)

---

R/draw-dm.R
tests/testthat/_snaps/datamodelr-code.md
tests/testthat/_snaps/datamodelr-code/nycflights13.dot
tests/testthat/_snaps/draw-dm.md
tests/testthat/test-datamodelr-code.R
tests/testthat/test-draw-dm.R

New and moved test, no new functionality.

chore: bdm tests

---

.github/.gitignore
.github/CONTRIBUTING.md
dm.Rproj

Fix #757
Using text by @moodymudskipper added on top of the tidy contributing guide

docs: Add contributing guide

---

R/examine-cardinalities.R
R/examine-constraints.R
man/dm_examine_cardinalities.Rd
man/dm_examine_constraints.Rd
tests/testthat/_snaps/examine-cardinalities.md
tests/testthat/test-examine-cardinalities.R

api: Stabilize `dm_examine_cardinalities()`

---

R/key-helpers.R
man/check_key.Rd
tests/testthat/_snaps/key-helpers.md
tests/testthat/test-key-helpers.R

Stabilize `check_key()`

---

R/key-helpers.R
man/check_key.Rd

check_key_impl0()

---

R/key-helpers.R
man/check_key.Rd
man/check_set_equality.Rd
man/check_subset.Rd
tests/testthat/helper-expectations.R
tests/testthat/test-key-helpers.R

api: Stabilize `check_subset()` and `check_set_equality()`

---

R/check-cardinalities.R
R/examine-cardinalities.R
R/global.R
R/key-helpers.R
man/check_set_equality.Rd
man/check_subset.Rd
man/examine_cardinality.Rd
tests/testthat/_snaps/check-cardinalities.md
tests/testthat/_snaps/key-helpers.md
tests/testthat/test-check-cardinalities.R

api: Stabilize `check_cardinality_...()` and `examine_cardinality()`

---

R/check-cardinalities.R
man/examine_cardinality.Rd
vignettes/howto-dm-rows.Rmd

Do they work? Yes: second bullet point of https://cynkra.github.io/dm/dev/news/index.html#documentation-0-3-0.

Add and use _...() aliases

---

R/add-tbl.R
R/dplyr-src.R
R/dplyr.R
R/draw-dm.R
R/examine-cardinalities.R
R/filter-dm.R
R/flatten.R
R/schema.R
R/select-tbl.R
R/tidyr.R
man/dm_flatten_to_tbl.Rd
man/dplyr_src.Rd
man/dplyr_table_manipulation.Rd
man/tidyr_table_manipulation.Rd

Use consistent markup for references

---

R/foreign-keys.R
R/primary-keys.R
R/table-surgery.R
man/decompose_table.Rd
man/dm_enum_fk_candidates.Rd
man/enum_pk_candidates.Rd
man/reunite_parent_child.Rd

to fully get rid of the "questioning" stage.

api: Turn all "questioning" functions to "experimental"

---

vignettes/dm.Rmd

docs: Improve contrast for display of `dm_financial()` (#1073)

---

R/dm.R
man/dm.Rd

dm_join_to_tbl() shouldn't be referenced anymore.

remove reference to deprecated function

---

R/filter-dm.R
R/financial.R
R/pixarfilms.R
R/ptype.R
R/table-surgery.R
man/decompose_table.Rd
man/dm_financial.Rd
man/dm_pixarfilms.Rd
man/dm_ptype.Rd
man/reunite_parent_child.Rd
vignettes/dm.Rmd
vignettes/howto-dm-copy.Rmd
vignettes/howto-dm-rows.Rmd
vignettes/out/dm.md
vignettes/out/howto-dm-copy.md
vignettes/out/howto-dm-rows.md

api: `dm_ptype()`, `dm_financial()` and `dm_pixarfilms()` are stable now

---

R/aaa-dbplyr.R
R/aaa-dplyr.R
R/bind.R
R/dm.R
R/validate.R
tests/testthat/_snaps/waldo.md
tests/testthat/test-waldo.R
vignettes/setup/setup.R

Unrelated commits

---

DESCRIPTION
tests/testthat/_snaps/dm.md
tests/testthat/_snaps/rows-dm.md
tests/testthat/test-dm.R
vignettes/tech-dm-keyed.Rmd

Stabilize snapshots after pillar update

---

pkgdown/_pkgdown.yml
vignettes/tech-dm-keyed.Rmd

Add keyed article

---

vignettes/tech-dm-class.Rmd

docs: Work around ANSI escape issues in CRAN rendering of vignette (#1156)

---

R/dplyr.R
scratch/demo-deconstruct.R

Fix group_by() + ungroup() for keyed

---

R/disambiguate.R
R/flatten.R
R/zzx-deprecated.R
man/dm_disambiguate_cols.Rd
tests/testthat/_snaps/disambiguate.md
tests/testthat/_snaps/dplyr.md
tests/testthat/helper-src.R
tests/testthat/test-dplyr.R
tests/testthat/test-flatten.R

feat!: `dm_disambiguate_cols()` gains a `.position` argument, disambiguates with suffix by default (#1293)

---

NEWS.md
R/disambiguate.R
R/dm_gui.R
R/global.R
R/gui-gui_server.R
R/zzx-deprecated.R
cran-comments.md
man/dm_disambiguate_cols.Rd
man/dm_gui.Rd
vignettes/setup/setup.R
vignettes/tech-dm-draw.Rmd

CRAN release v1.0.0

---

vignettes/tech-dm-keyed.Rmd

Add use case for deconstruct

---

NEWS.md
R/gui-dmSVG.R
R/gui-gui_global.R
R/gui-gui_ui.R
README.Rmd
README.md
cran-comments.md

CRAN release v1.0.1

---

tests/testthat/_snaps/rows-dm.md
tests/testthat/test-rows-dm.R

chore: Reenable `dm_rows_update()` test

---

R/pack_join.R
tests/testthat/_snaps/pack_join.md

feat: `pack_join(keep = TRUE)` keeps keys of `y` in the resulting packed column

---

tests/testthat/_snaps/duckdb/db-interface.md
tests/testthat/test-db-interface.R
tests/testthat/test-learn.R

chore: Fix compatibility with duckdb 0.5.0

---

R/paste.R
tests/testthat/_snaps/paste.md
tests/testthat/test-paste.R

fix: `dm_paste()` gives correct output for factor columns with many levels

---

NEWS.md
cran-comments.md

CRAN release v1.0.2

---

NEWS.md
cran-comments.md

CRAN release v1.0.3

---

DESCRIPTION
R/check-cardinalities.R
tests/testthat/_snaps/add-tbl.md
tests/testthat/_snaps/bind.md
tests/testthat/_snaps/check-cardinalities.md
tests/testthat/_snaps/code-generation.md
tests/testthat/_snaps/dm.md
tests/testthat/_snaps/examine-cardinalities.md
tests/testthat/_snaps/examine-constraints.md
tests/testthat/_snaps/key-helpers.md
tests/testthat/_snaps/paste.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/test-learn.R

chore: Require lifecycle >= 1.0.3

---

R/primary-keys.R
tests/testthat/_snaps/primary-keys.md
tests/testthat/test-primary-keys.R

feat: Improve error message for `dm_add_pk()` when the `columns` argument is missing

---

R/rows-dm.R

chore: Clean up `dm_rows_append()` implementation

---

R/test-dm.R

chore: Fix r-devel builds

---

NEWS.md
cran-comments.md
tests/testthat/test-pool-support.R

CRAN release v1.0.4

---

pkgdown/_pkgdown.yml

docs: add alternative text to author images for pkgdown website

---

tests/testthat/_snaps/df/flatten.md
tests/testthat/_snaps/duckdb/flatten.md
tests/testthat/_snaps/duckdb/table-surgery.md
tests/testthat/_snaps/maria/flatten.md
tests/testthat/_snaps/mssql/flatten.md
tests/testthat/_snaps/postgres/flatten.md
tests/testthat/_snaps/sqlite/flatten.md
tests/testthat/test-flatten.R

Fix typo in tests

---

.github/workflows/R-CMD-check.yaml
R/dplyr.R
R/keys.R
tests/testthat/_snaps/duckdb/flatten.md
tests/testthat/helper-src.R
tests/testthat/test-bind.R
tests/testthat/test-dm.R
tests/testthat/test-flatten.R

chore: Fix tests

---

DESCRIPTION
vignettes/dm.Rmd
vignettes/flights_dm_w_many_keys_and_color.svg
vignettes/howto-dm-copy.Rmd
vignettes/howto-dm-rows.Rmd
vignettes/howto-dm-theory.Rmd
vignettes/out/tech-dm-filter.md
vignettes/setup/setup.R
vignettes/tech-dm-filter.Rmd
vignettes/tech-dm-join.Rmd
vignettes/tech-dm-keyed.Rmd
vignettes/tech-dm-low-level.Rmd
vignettes/tech-dm-zoom.Rmd

chore: Remove tidyverse dependency

---

tests/testthat/_snaps/deconstruct.md
tests/testthat/helper-jsonlite.R
tests/testthat/test-deconstruct.R

chore: Compatibility with dev jsonlite

---

NEWS.md
cran-comments.md

CRAN release v1.0.5

---

vignettes/dm.Rmd
vignettes/howto-dm-theory.Rmd

I noticed a few minor mistakes and grammatical errors when reading the vignettes, so have corrected them in this PR.

docs: Vignette corrections

---

.Rbuildignore
.github/CONTRIBUTING.md
docker-compose.yml
tests/testthat/helper-config-db.R
tests/testthat/helper-src.R

for testing databases.
@mgirlich @jangorecki: Does that work for you?

docs: Describe Docker setup

---

R/build_copy_queries.R
R/db-interface.R

avoid `collect()` on `dm`, run tests

chore: In `copy_dm_to()`, call `collect()` only when copying data, table by table

---

DESCRIPTION
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/_snaps/tidyselect.md
tests/testthat/_snaps/unique-keys.md
tests/testthat/test-unique-keys.R

chore: Adapt to dev tidyselect

---

R/build_copy_queries.R
R/db-interface.R

chore: Move `ptype_dm` to `build_copy_queries()`

---

DESCRIPTION
NEWS.md
R/descriptions.R
R/select-tbl.R
cran-comments.md
tests/testthat/_snaps/foreign-keys.md
tests/testthat/_snaps/primary-keys.md
tests/testthat/_snaps/tidyselect.md
tests/testthat/test-dm.R
tests/testthat/test-foreign-keys.R
tests/testthat/test-primary-keys.R
tests/testthat/test-tidyselect.R

CRAN release v1.0.6

---

.github/workflows/R-CMD-check.yaml
.github/workflows/custom/after-install/action.yml

feat: Test MySQL on GHA

---

R/dm.R

chore: Add ellipsis to `tbl_sum()` signature

---

R/dm.R
R/dm_get_tables.R
R/json_nest.R
R/json_nest_join.R
R/json_pack.R
R/json_pack_join.R
R/pack_join.R

feat!: Add `check_dots_empty()` calls

---

R/rows-dm.R

Add placeholder error messages

---

R/dm.R
tests/testthat/_snaps/dm.md

docs: `collect.zoomed_dm()` shows a more helpful error message

---

R/dm_nest_tbl.R
R/dm_wrap.R
R/new_ticker.R

fix: Minor fixes in `dm_pack_tbl()` and `dm_unwrap_tbl()`

---

Makefile
tests/testthat/_snaps/postgres.md
tests/testthat/test-postgres.R
tests/testthat/test-rows-dm.R

Apply individual commits when good

Tinkering once more

---

docker-compose.yml
tests/testthat/_snaps/bind.md
tests/testthat/_snaps/datamodelr-code.md
tests/testthat/_snaps/deconstruct.md
tests/testthat/_snaps/dm.md
tests/testthat/_snaps/paste.md
tests/testthat/_snaps/unique-keys.md
tests/testthat/helper-src.R

Baby steps

---

R/cache.R
R/error-helpers.R
R/gui-zzz.R
R/zzz.R
tests/testthat/helper-src.R

More refactorings

---

DESCRIPTION
R/db-helpers.R
R/mariadb.R

chore: Indicate MySQL server, bump to dev version of RMariaDB, work around tidyverse/dbplyr#1190

---

R/db-helpers.R
docker-compose.yml
tests/testthat/_snaps/dm.md
tests/testthat/_snaps/dplyr.md
tests/testthat/_snaps/duckdb.md
tests/testthat/_snaps/maria.md
tests/testthat/_snaps/mssql.md
tests/testthat/_snaps/sqlite.md
tests/testthat/_snaps/zoom.md
tests/testthat/helper-src.R
tests/testthat/helper-sync.R
tests/testthat/test-duckdb.R
tests/testthat/test-maria.R
tests/testthat/test-mssql.R
tests/testthat/test-sqlite.R

chore: Stabilize tests, add snapshot tests for `dm_sql()` for all databases

---

R/copy_dm_to.R
R/dm.R
R/globals.R
man/dm_sql.Rd
tests/testthat/_snaps/copy_dm_to.md
tests/testthat/_snaps/duckdb.md
tests/testthat/_snaps/learn.md
tests/testthat/_snaps/maria.md
tests/testthat/_snaps/mssql.md
tests/testthat/_snaps/postgres.md
tests/testthat/_snaps/sqlite.md
tests/testthat/helper-src.R

feat: Reuse existing `build_copy_queries()` code for `dm_sql()`

---

R/dm_sql.R
R/foreign-keys.R
man/dm_add_fk.Rd
tests/testthat/_snaps/duckdb.md
tests/testthat/_snaps/graph.md
tests/testthat/_snaps/maria.md
tests/testthat/_snaps/mssql.md
tests/testthat/_snaps/postgres.md
tests/testthat/_snaps/sqlite.md
tests/testthat/helper-src.R
tests/testthat/test-graph.R
tests/testthat/test-learn.R

chore: Stabilize and improve tests

---

R/dm.R
R/nycflights13.R
R/pixarfilms.R
R/zoom.R
man/dm_nycflights13.Rd
man/dm_pixarfilms.Rd
man/dm_zoom_to.Rd
man/glimpse.dm.Rd

chore: Remove curly braces. add `\pkg`

---

tests/testthat/helper-src.R
tests/testthat/test-add-tbl.R
tests/testthat/test-bind.R
tests/testthat/test-db-helpers.R
tests/testthat/test-db-interface.R
tests/testthat/test-deconstruct.R
tests/testthat/test-descriptions.R
tests/testthat/test-dm.R
tests/testthat/test-dm_pixarfilms.R
tests/testthat/test-dplyr-src.R
tests/testthat/test-dplyr.R
tests/testthat/test-draw-dm.R
tests/testthat/test-examine-constraints.R
tests/testthat/test-flatten.R
tests/testthat/test-foreign-keys.R
tests/testthat/test-learn.R
tests/testthat/test-nest.R
tests/testthat/test-paste.R
tests/testthat/test-rows-dm.R
tests/testthat/test-select-tbl.R
tests/testthat/test-validate.R
tests/testthat/test-zoom.R
tests/testthat/test-zzx-deprecated.R
tests/testthat/test_dm_from_con.R

test: Remove most skips from tests

---

DESCRIPTION
NEWS.md
R/draw-dm.R
cran-comments.md
man/dm_set_colors.Rd

CRAN release v1.0.7

---

R/standalone-check_suggested.R

Remove outdated message argument description and add example of how to specify version.

docs: Update documentation of `check_suggested()`

---

R/dm_sql.R
tests/testthat/_snaps/dm_sql.md
tests/testthat/_snaps/duckdb.md

feat: Warn about DuckDB not supporting autoincrementing primary keys

---

.github/workflows/R-CMD-check.yaml

test: Add final step that collects all checks

---

.github/workflows/R-CMD-check.yaml

test: Remove final step, requiring all checks to pass

---

DESCRIPTION
NEWS.md
cran-comments.md

CRAN release v1.0.8
